version: '3'

services:
  golang-workspace:
    container_name: golang-workspace
    build: ./workspace #dir
    volumes:
      - "./app:/home/golang/app"
      - "./go:/home/golang/go"
    ports:
      - "10080:22"
      - "8080:8080"
    tty: true #keep container up
    privileged: true
